// Global Configuration for GNSS Data Downloader
const globalConfig = {
  gnssStations: [
    {
      code: 'ALGO',
      name: 'Algonquin Park, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'ALIC',
      name: 'Alice Springs, Australia',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'ANKR',
      name: 'Ankara, Turkey',
      country: 'Turkey',
      region: 'Europe/Asia',
    },
    {
      code: 'ARTU',
      name: 'Arti, Russia',
      country: 'Russia',
      region: 'Asia',
    },
    {
      code: 'BADG',
      name: 'Badger Hill, Antarctica',
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'BAHR',
      name: 'Bahrain',
      country: 'Bahrain',
      region: 'Middle East',
    },
    {
      code: 'BJFS',
      name: 'Beijing, China',
      country: 'China',
      region: 'Asia',
    },
    {
      code: 'BOGT',
      name: 'Bogota, Colombia',
      country: 'Colombia',
      region: 'South America',
    },
    {
      code: 'BRAZ',
      name: 'Brasilia, Brazil',
      country: 'Brazil',
      region: 'South America',
    },
    {
      code: 'BRMU',
      name: 'Bermuda',
      country: 'Bermuda',
      region: 'North America',
    },
    {
      code: 'BRST',
      name: 'Brest, France',
      country: 'France',
      region: 'Europe',
    },
    {
      code: 'CASB',
      name: 'Casey Base, Antarctica',
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'CCJM',
      name: 'Chichijima, Japan',
      country: 'Japan',
      region: 'Asia',
    },
    {
      code: 'CEDU',
      name: 'Ceduna, Australia',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'CHAT',
      name: 'Chatham Island, New Zealand',
      country: 'New Zealand',
      region: 'Oceania',
    },
    {
      code: 'CHUR',
      name: 'Churchill, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'CRO1',
      name: 'Christiansted, Virgin Islands',
      country: 'Virgin Islands',
      region: 'North America',
    },
    {
      code: 'DARW',
      name: 'Darwin, Australia',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'DAV1',
      name: 'Davis Base, Antarctica',
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'DUBO',
      name: "Dumont d'Urville, Antarctica",
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'FAIR',
      name: 'Fairbanks, Alaska',
      country: 'USA',
      region: 'North America',
    },
    {
      code: 'FLIN',
      name: 'Flin Flon, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'FORT',
      name: 'Fortaleza, Brazil',
      country: 'Brazil',
      region: 'South America',
    },
    {
      code: 'GLPS',
      name: 'Galapagos Islands, Ecuador',
      country: 'Ecuador',
      region: 'South America',
    },
    {
      code: 'GLSV',
      name: 'Kiev, Ukraine',
      country: 'Ukraine',
      region: 'Europe',
    },
    {
      code: 'GODE',
      name: 'Goddard Space Flight Center, USA',
      country: 'USA',
      region: 'North America',
    },
    {
      code: 'GOLD',
      name: 'Goldstone, California',
      country: 'USA',
      region: 'North America',
    },
    {
      code: 'GOPE',
      name: 'Ondrejov, Czech Republic',
      country: 'Czech Republic',
      region: 'Europe',
    },
    {
      code: 'GRAS',
      name: 'Grasse, France',
      country: 'France',
      region: 'Europe',
    },
    {
      code: 'GUAM',
      name: 'Guam',
      country: 'Guam',
      region: 'Oceania',
    },
    {
      code: 'HARB',
      name: 'Hartebeesthoek, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'HERS',
      name: 'Herstmonceux, UK',
      country: 'United Kingdom',
      region: 'Europe',
    },
    {
      code: 'HOB2',
      name: 'Hobart, Australia',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'HOFN',
      name: 'Hofn, Iceland',
      country: 'Iceland',
      region: 'Europe',
    },
    {
      code: 'HRAO',
      name: 'Hartebeesthoek Radio Astronomy Observatory, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'HYDE',
      name: 'Hyderabad, India',
      country: 'India',
      region: 'Asia',
    },
    {
      code: 'IISC',
      name: 'Bangalore, India',
      country: 'India',
      region: 'Asia',
    },
    {
      code: 'IRKT',
      name: 'Irkutsk, Russia',
      country: 'Russia',
      region: 'Asia',
    },
    {
      code: 'JPLM',
      name: 'JPL Mesa, California',
      country: 'USA',
      region: 'North America',
    },
    {
      code: 'KARR',
      name: 'Karratha, Australia',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'KELY',
      name: 'Kellyville, Greenland',
      country: 'Greenland',
      region: 'North America',
    },
    {
      code: 'KERG',
      name: 'Kerguelen Islands, France',
      country: 'France',
      region: 'Antarctica',
    },
    {
      code: 'KIRU',
      name: 'Kiruna, Sweden',
      country: 'Sweden',
      region: 'Europe',
    },
    {
      code: 'KITG',
      name: 'Kitgum, Uganda',
      country: 'Uganda',
      region: 'Africa',
    },
    {
      code: 'KOKB',
      name: 'Kokee Park, Hawaii',
      country: 'USA',
      region: 'Oceania',
    },
    {
      code: 'KOUG',
      name: 'Kourou, French Guiana',
      country: 'French Guiana',
      region: 'South America',
    },
    {
      code: 'KOUR',
      name: 'Kourou, French Guiana',
      country: 'French Guiana',
      region: 'South America',
    },
    {
      code: 'LAE1',
      name: 'Lae, Papua New Guinea',
      country: 'Papua New Guinea',
      region: 'Oceania',
    },
    {
      code: 'LAMA',
      name: 'Lamkowko, Poland',
      country: 'Poland',
      region: 'Europe',
    },
    {
      code: 'LHAZ',
      name: 'Lhasa, Tibet',
      country: 'China',
      region: 'Asia',
    },
    {
      code: 'MAC1',
      name: 'Macquarie Island, Australia',
      country: 'Australia',
      region: 'Antarctica',
    },
    {
      code: 'MAD2',
      name: 'Madrid, Spain',
      country: 'Spain',
      region: 'Europe',
    },
    {
      code: 'MALA',
      name: 'Malargue, Argentina',
      country: 'Argentina',
      region: 'South America',
    },
    {
      code: 'MAS1',
      name: 'Maspalomas, Spain',
      country: 'Spain',
      region: 'Europe',
    },
    {
      code: 'MAW1',
      name: 'Mawson Base, Antarctica',
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'MCM4',
      name: 'McMurdo Station, Antarctica',
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'MDVJ',
      name: 'Mendeleevo, Russia',
      country: 'Russia',
      region: 'Europe',
    },
    {
      code: 'MIZU',
      name: 'Mizusawa, Japan',
      country: 'Japan',
      region: 'Asia',
    },
    {
      code: 'MOBK',
      name: 'Mobukayama, Japan',
      country: 'Japan',
      region: 'Asia',
    },
    {
      code: 'NKLG',
      name: "N'Koltang, Gabon",
      country: 'Gabon',
      region: 'Africa',
    },
    {
      code: 'NOT1',
      name: 'Noto, Italy',
      country: 'Italy',
      region: 'Europe',
    },
    {
      code: 'NOTO',
      name: 'Noto, Italy',
      country: 'Italy',
      region: 'Europe',
    },
    {
      code: 'NPLD',
      name: 'North Pole Environmental Observatory',
      country: 'Arctic',
      region: 'Arctic',
    },
    {
      code: 'NYA1',
      name: 'Ny-Alesund, Svalbard',
      country: 'Norway',
      region: 'Arctic',
    },
    {
      code: 'NYAL',
      name: 'Ny-Alesund, Svalbard',
      country: 'Norway',
      region: 'Arctic',
    },
    {
      code: 'OHI2',
      name: "O'Higgins Base, Antarctica",
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'ONSA',
      name: 'Onsala, Sweden',
      country: 'Sweden',
      region: 'Europe',
    },
    {
      code: 'PERT',
      name: 'Perth, Australia',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'PETS',
      name: 'Petropavlovsk, Russia',
      country: 'Russia',
      region: 'Asia',
    },
    {
      code: 'PIE1',
      name: 'Pietown, New Mexico',
      country: 'USA',
      region: 'North America',
    },
    {
      code: 'PIMO',
      name: 'Quezon City, Philippines',
      country: 'Philippines',
      region: 'Asia',
    },
    {
      code: 'POL2',
      name: 'Bishkek, Kyrgyzstan',
      country: 'Kyrgyzstan',
      region: 'Asia',
    },
    {
      code: 'POLV',
      name: 'Poltava, Ukraine',
      country: 'Ukraine',
      region: 'Europe',
    },
    {
      code: 'POTS',
      name: 'Potsdam, Germany',
      country: 'Germany',
      region: 'Europe',
    },
    {
      code: 'QUIN',
      name: 'Quincy, California',
      country: 'USA',
      region: 'North America',
    },
    {
      code: 'RBAY',
      name: 'Richards Bay, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'REDU',
      name: 'Redu, Belgium',
      country: 'Belgium',
      region: 'Europe',
    },
    {
      code: 'REYK',
      name: 'Reykjavik, Iceland',
      country: 'Iceland',
      region: 'Europe',
    },
    {
      code: 'SANT',
      name: 'Santiago, Chile',
      country: 'Chile',
      region: 'South America',
    },
    {
      code: 'SASK',
      name: 'Saskatoon, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'SCH2',
      name: 'Schefferville, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'SCUB',
      name: 'Santiago de Cuba, Cuba',
      country: 'Cuba',
      region: 'North America',
    },
    {
      code: 'SEY1',
      name: 'Mahe, Seychelles',
      country: 'Seychelles',
      region: 'Africa',
    },
    {
      code: 'SFER',
      name: 'San Fernando, Spain',
      country: 'Spain',
      region: 'Europe',
    },
    {
      code: 'SHAO',
      name: 'Shanghai, China',
      country: 'China',
      region: 'Asia',
    },
    {
      code: 'STHL',
      name: 'St. Helena',
      country: 'St. Helena',
      region: 'Africa',
    },
    {
      code: 'STJ3',
      name: "St. John's, Canada",
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'SUTH',
      name: 'Sutherland, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'SYOG',
      name: 'Syowa Base, Antarctica',
      country: 'Antarctica',
      region: 'Antarctica',
    },
    {
      code: 'TASH',
      name: 'Tashkent, Uzbekistan',
      country: 'Uzbekistan',
      region: 'Asia',
    },
    {
      code: 'THU3',
      name: 'Thule, Greenland',
      country: 'Greenland',
      region: 'Arctic',
    },
    {
      code: 'TIDB',
      name: 'Tidbinbilla, Australia',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'TONG',
      name: 'Tongatapu, Tonga',
      country: 'Tonga',
      region: 'Oceania',
    },
    {
      code: 'TORP',
      name: 'Torp, Norway',
      country: 'Norway',
      region: 'Europe',
    },
    {
      code: 'TRAB',
      name: 'Trabzon, Turkey',
      country: 'Turkey',
      region: 'Europe/Asia',
    },
    {
      code: 'TROM',
      name: 'Tromso, Norway',
      country: 'Norway',
      region: 'Europe',
    },
    {
      code: 'TSKB',
      name: 'Tsukuba, Japan',
      country: 'Japan',
      region: 'Asia',
    },
    {
      code: 'UCAL',
      name: 'Calgary, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'UNSA',
      name: 'Salta, Argentina',
      country: 'Argentina',
      region: 'South America',
    },
    {
      code: 'USUD',
      name: 'Usuda, Japan',
      country: 'Japan',
      region: 'Asia',
    },
    {
      code: 'VILL',
      name: 'Villafranca, Spain',
      country: 'Spain',
      region: 'Europe',
    },
    {
      code: 'WIND',
      name: 'Windhoek, Namibia',
      country: 'Namibia',
      region: 'Africa',
    },
    {
      code: 'WTZR',
      name: 'Wettzell, Germany',
      country: 'Germany',
      region: 'Europe',
    },
    {
      code: 'YELL',
      name: 'Yellowknife, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'YEMA',
      name: 'Yeman, Russia',
      country: 'Russia',
      region: 'Asia',
    },
    {
      code: 'YSSK',
      name: 'Yuzhno-Sakhalinsk, Russia',
      country: 'Russia',
      region: 'Asia',
    },
    {
      code: 'ZECK',
      name: 'Zelenchukskaya, Russia',
      country: 'Russia',
      region: 'Europe',
    },
    {
      code: 'ZIMM',
      name: 'Zimmerwald, Switzerland',
      country: 'Switzerland',
      region: 'Europe',
    },
    // Additional African stations
    {
      code: 'ABPO',
      name: 'Abidjan, Ivory Coast',
      country: 'Ivory Coast',
      region: 'Africa',
    },
    {
      code: 'ADIS',
      name: 'Addis Ababa, Ethiopia',
      country: 'Ethiopia',
      region: 'Africa',
    },
    {
      code: 'ASCG',
      name: 'Ascension Island',
      country: 'St. Helena',
      region: 'Africa',
    },
    {
      code: 'BAMF',
      name: 'Bamako, Mali',
      country: 'Mali',
      region: 'Africa',
    },
    {
      code: 'BANT',
      name: 'Bantry Bay, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'BOTS',
      name: 'Gaborone, Botswana',
      country: 'Botswana',
      region: 'Africa',
    },
    {
      code: 'CONZ',
      name: 'Conceição, Angola',
      country: 'Angola',
      region: 'Africa',
    },
    {
      code: 'CPVG',
      name: 'Cape Verde',
      country: 'Cape Verde',
      region: 'Africa',
    },
    {
      code: 'DAKR',
      name: 'Dakar, Senegal',
      country: 'Senegal',
      region: 'Africa',
    },
    {
      code: 'DJIG',
      name: 'Djibouti',
      country: 'Djibouti',
      region: 'Africa',
    },
    {
      code: 'EBBE',
      name: 'Ebbenangor, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'HNUS',
      name: 'Hermanus, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'JNAV',
      name: 'Johannesburg, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'KANO',
      name: 'Kano, Nigeria',
      country: 'Nigeria',
      region: 'Africa',
    },
    {
      code: 'LAGS',
      name: 'Lagos, Nigeria',
      country: 'Nigeria',
      region: 'Africa',
    },
    {
      code: 'LAMU',
      name: 'Lamu, Kenya',
      country: 'Kenya',
      region: 'Africa',
    },
    {
      code: 'LOME',
      name: 'Lomé, Togo',
      country: 'Togo',
      region: 'Africa',
    },
    {
      code: 'MALI',
      name: 'Malindi, Kenya',
      country: 'Kenya',
      region: 'Africa',
    },
    {
      code: 'MAPZ',
      name: 'Maputo, Mozambique',
      country: 'Mozambique',
      region: 'Africa',
    },
    {
      code: 'MBAR',
      name: 'Mbarara, Uganda',
      country: 'Uganda',
      region: 'Africa',
    },
    {
      code: 'MFKG',
      name: 'Mafikeng, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'MORC',
      name: 'Morocco',
      country: 'Morocco',
      region: 'Africa',
    },
    {
      code: 'NAMA',
      name: 'Windhoek, Namibia',
      country: 'Namibia',
      region: 'Africa',
    },
    {
      code: 'NICO',
      name: 'Nicosia, Cyprus',
      country: 'Cyprus',
      region: 'Europe',
    },
    {
      code: 'NOTO',
      name: 'Noto, Sicily',
      country: 'Italy',
      region: 'Europe',
    },
    {
      code: 'RABK',
      name: 'Rabat, Morocco',
      country: 'Morocco',
      region: 'Africa',
    },
    {
      code: 'REUN',
      name: 'Reunion Island',
      country: 'France',
      region: 'Africa',
    },
    {
      code: 'RWND',
      name: 'Kigali, Rwanda',
      country: 'Rwanda',
      region: 'Africa',
    },
    {
      code: 'SEYZ',
      name: 'Seychelles',
      country: 'Seychelles',
      region: 'Africa',
    },
    {
      code: 'SUTM',
      name: 'Sutherland, South Africa',
      country: 'South Africa',
      region: 'Africa',
    },
    {
      code: 'TANA',
      name: 'Antananarivo, Madagascar',
      country: 'Madagascar',
      region: 'Africa',
    },
    {
      code: 'TUNY',
      name: 'Tunis, Tunisia',
      country: 'Tunisia',
      region: 'Africa',
    },
    {
      code: 'YEBE',
      name: 'Yebes, Spain',
      country: 'Spain',
      region: 'Europe',
    },
    {
      code: 'ZAMB',
      name: 'Lusaka, Zambia',
      country: 'Zambia',
      region: 'Africa',
    },
    // Additional Island stations
    {
      code: 'AZOR',
      name: 'Azores, Portugal',
      country: 'Portugal',
      region: 'Europe',
    },
    {
      code: 'BERM',
      name: 'Bermuda',
      country: 'Bermuda',
      region: 'North America',
    },
    {
      code: 'CAGL',
      name: 'Cagliari, Sardinia',
      country: 'Italy',
      region: 'Europe',
    },
    {
      code: 'COCO',
      name: 'Cocos Islands',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'COOK',
      name: 'Cook Islands',
      country: 'Cook Islands',
      region: 'Oceania',
    },
    {
      code: 'CORS',
      name: 'Corsica, France',
      country: 'France',
      region: 'Europe',
    },
    {
      code: 'CRAO',
      name: 'Crimea, Ukraine',
      country: 'Ukraine',
      region: 'Europe',
    },
    {
      code: 'CREU',
      name: 'Crete, Greece',
      country: 'Greece',
      region: 'Europe',
    },
    {
      code: 'CURA',
      name: 'Curacao',
      country: 'Netherlands',
      region: 'North America',
    },
    {
      code: 'CYP1',
      name: 'Cyprus',
      country: 'Cyprus',
      region: 'Europe',
    },
    {
      code: 'DGAR',
      name: 'Diego Garcia',
      country: 'UK Territory',
      region: 'Asia',
    },
    {
      code: 'EISL',
      name: 'Easter Island',
      country: 'Chile',
      region: 'South America',
    },
    {
      code: 'FALK',
      name: 'Falkland Islands',
      country: 'UK Territory',
      region: 'South America',
    },
    {
      code: 'FAUG',
      name: 'Faial, Azores',
      country: 'Portugal',
      region: 'Europe',
    },
    {
      code: 'FLOR',
      name: 'Flores, Azores',
      country: 'Portugal',
      region: 'Europe',
    },
    {
      code: 'GALA',
      name: 'Galapagos Islands',
      country: 'Ecuador',
      region: 'South America',
    },
    {
      code: 'GIBR',
      name: 'Gibraltar',
      country: 'UK Territory',
      region: 'Europe',
    },
    {
      code: 'GLAD',
      name: 'Greenland',
      country: 'Greenland',
      region: 'Arctic',
    },
    {
      code: 'GODZ',
      name: 'Godhavn, Greenland',
      country: 'Greenland',
      region: 'Arctic',
    },
    {
      code: 'GUAD',
      name: 'Guadeloupe',
      country: 'France',
      region: 'North America',
    },
    {
      code: 'HAIT',
      name: 'Haiti',
      country: 'Haiti',
      region: 'North America',
    },
    {
      code: 'HAWA',
      name: 'Hawaii',
      country: 'USA',
      region: 'Oceania',
    },
    {
      code: 'HOBE',
      name: 'Hobart, Tasmania',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'ICED',
      name: 'Iceland',
      country: 'Iceland',
      region: 'Europe',
    },
    {
      code: 'IRLD',
      name: 'Ireland',
      country: 'Ireland',
      region: 'Europe',
    },
    {
      code: 'JAMA',
      name: 'Jamaica',
      country: 'Jamaica',
      region: 'North America',
    },
    {
      code: 'KIWA',
      name: 'Kiritimati, Kiribati',
      country: 'Kiribati',
      region: 'Oceania',
    },
    {
      code: 'KOKV',
      name: 'Kwajalein, Marshall Islands',
      country: 'Marshall Islands',
      region: 'Oceania',
    },
    {
      code: 'LPAL',
      name: 'La Palma, Canary Islands',
      country: 'Spain',
      region: 'Africa',
    },
    {
      code: 'MADR',
      name: 'Madeira, Portugal',
      country: 'Portugal',
      region: 'Europe',
    },
    {
      code: 'MALL',
      name: 'Mallorca, Spain',
      country: 'Spain',
      region: 'Europe',
    },
    {
      code: 'MALT',
      name: 'Malta',
      country: 'Malta',
      region: 'Europe',
    },
    {
      code: 'MARS',
      name: 'Marseille, France',
      country: 'France',
      region: 'Europe',
    },
    {
      code: 'MART',
      name: 'Martinique',
      country: 'France',
      region: 'North America',
    },
    {
      code: 'MAUR',
      name: 'Mauritius',
      country: 'Mauritius',
      region: 'Africa',
    },
    {
      code: 'MAYG',
      name: 'Mayotte',
      country: 'France',
      region: 'Africa',
    },
    {
      code: 'NANO',
      name: 'Nanoose, Vancouver Island',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'NAUR',
      name: 'Nauru',
      country: 'Nauru',
      region: 'Oceania',
    },
    {
      code: 'NEUF',
      name: 'Newfoundland, Canada',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'NEWC',
      name: 'New Caledonia',
      country: 'France',
      region: 'Oceania',
    },
    {
      code: 'NIUE',
      name: 'Niue',
      country: 'Niue',
      region: 'Oceania',
    },
    {
      code: 'NORF',
      name: 'Norfolk Island',
      country: 'Australia',
      region: 'Oceania',
    },
    {
      code: 'NRMD',
      name: 'Nord, Greenland',
      country: 'Greenland',
      region: 'Arctic',
    },
    {
      code: 'NUKA',
      name: "Nuku'alofa, Tonga",
      country: 'Tonga',
      region: 'Oceania',
    },
    {
      code: 'PALB',
      name: 'Palau',
      country: 'Palau',
      region: 'Oceania',
    },
    {
      code: 'PAPE',
      name: 'Papeete, French Polynesia',
      country: 'France',
      region: 'Oceania',
    },
    {
      code: 'PRIN',
      name: 'Prince Edward Island',
      country: 'Canada',
      region: 'North America',
    },
    {
      code: 'PRIC',
      name: 'Prince Edward Island',
      country: 'South Africa',
      region: 'Antarctica',
    },
    {
      code: 'RAEG',
      name: 'Raes Island',
      country: 'Canada',
      region: 'Arctic',
    },
    {
      code: 'RIOG',
      name: 'Rio Grande, Argentina',
      country: 'Argentina',
      region: 'South America',
    },
    {
      code: 'SARD',
      name: 'Sardinia, Italy',
      country: 'Italy',
      region: 'Europe',
    },
    {
      code: 'SCIL',
      name: 'Scilly Isles, UK',
      country: 'United Kingdom',
      region: 'Europe',
    },
    {
      code: 'SHET',
      name: 'Shetland Islands, UK',
      country: 'United Kingdom',
      region: 'Europe',
    },
    {
      code: 'SICI',
      name: 'Sicily, Italy',
      country: 'Italy',
      region: 'Europe',
    },
    {
      code: 'STIO',
      name: 'St. Iona, UK',
      country: 'United Kingdom',
      region: 'Europe',
    },
    {
      code: 'STVN',
      name: 'St. Vincent',
      country: 'St. Vincent',
      region: 'North America',
    },
    {
      code: 'TAIW',
      name: 'Taiwan',
      country: 'Taiwan',
      region: 'Asia',
    },
    {
      code: 'TENE',
      name: 'Tenerife, Canary Islands',
      country: 'Spain',
      region: 'Africa',
    },
    {
      code: 'THUL',
      name: 'Thule, Greenland',
      country: 'Greenland',
      region: 'Arctic',
    },
    {
      code: 'TRIN',
      name: 'Trinidad and Tobago',
      country: 'Trinidad and Tobago',
      region: 'North America',
    },
    {
      code: 'TRUK',
      name: 'Chuuk, Micronesia',
      country: 'Micronesia',
      region: 'Oceania',
    },
    {
      code: 'VANU',
      name: 'Vanuatu',
      country: 'Vanuatu',
      region: 'Oceania',
    },
    {
      code: 'WAKE',
      name: 'Wake Island',
      country: 'USA',
      region: 'Oceania',
    },
    {
      code: 'WALL',
      name: 'Wallis and Futuna',
      country: 'France',
      region: 'Oceania',
    },
  ],
  dataSources: {
    sonel: {
      name: 'SONEL',
      fullName: "Système d'Observation du Niveau des Eaux Littorales",
      description: 'Coastal sea level observation system',
      theme: {
        primary: '#3B82F6',
        secondary: '#EBF4FF',
        accent: '#1E40AF',
        gradient: 'linear-gradient(135deg, #3B82F6, #1E40AF)',
      },
      icon: 'fas fa-water',
      baseUrl: 'https://www.sonel.org',
      fileTypes: ['rinex', 'hatanaka'],
      requiresAuth: false,
      downloadMethod: 'iframe',
    },
    nasa: {
      name: 'NASA CDDIS',
      fullName: 'NASA Crustal Dynamics Data Information System',
      description: "NASA's archive of space geodesy data",
      theme: {
        primary: '#8B5CF6',
        secondary: '#F3F4F6',
        accent: '#6D28D9',
        gradient: 'linear-gradient(135deg, #8B5CF6, #6D28D9)',
      },
      icon: 'fas fa-satellite',
      baseUrl: 'https://cddis.nasa.gov',
      fileTypes: [
        {
          extension: 'd.Z',
          description: 'Daily observation data (Hatanaka compressed)',
        },
        {
          extension: 'n.Z',
          description: 'Navigation/broadcast ephemeris data',
        },
        {
          extension: 'g.Z',
          description: 'GLONASS navigation data',
        },
        {
          extension: 'h.Z',
          description: 'High-rate observation data',
        },
      ],
      requiresAuth: true,
      authUrl: 'https://urs.earthdata.nasa.gov/',
      downloadMethod: 'direct',
    },
    unavco: {
      name: 'UNAVCO',
      fullName: 'UNAVCO Data Archive',
      description: 'University NAVSTAR Consortium data archive',
      theme: {
        primary: '#10B981',
        secondary: '#F0FDF4',
        accent: '#047857',
        gradient: 'linear-gradient(135deg, #10B981, #047857)',
      },
      icon: 'fas fa-globe-americas',
      baseUrl: 'https://data.unavco.org',
      fileTypes: [
        {
          extension: 'obs',
          description: 'Observation data files',
          category: 'obs',
        },
        {
          extension: 'd.Z',
          description: 'Daily observation data (Hatanaka compressed)',
          category: 'obs',
        },
        {
          extension: 'nav',
          description: 'Navigation/broadcast ephemeris files',
          category: 'nav',
        },
        {
          extension: 'n.Z',
          description: 'Navigation data (compressed)',
          category: 'nav',
        },
      ],
      requiresAuth: true,
      authUrl: 'https://www.unavco.org/account/',
      downloadMethod: 'direct',
    },
  },
  ui: {
    fonts: {
      primary:
        "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monospace: "'JetBrains Mono', 'Fira Code', 'Courier New', monospace",
    },
    colors: {
      background: '#f8fafc',
      surface: '#ffffff',
      text: {
        primary: '#1f2937',
        secondary: '#6b7280',
        muted: '#9ca3af',
      },
      border: '#e5e7eb',
      shadow: 'rgba(0, 0, 0, 0.1)',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    borderRadius: {
      sm: '0.375rem',
      md: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    breakpoints: {
      mobile: '768px',
      tablet: '1024px',
      desktop: '1280px',
    },
  },
  browsers: {
    chrome: {
      name: 'Chrome',
      icon: 'fab fa-chrome',
      color: '#DB4437',
    },
    firefox: {
      name: 'Firefox',
      icon: 'fab fa-firefox',
      color: '#FF9500',
    },
    safari: {
      name: 'Safari',
      icon: 'fab fa-safari',
      color: '#007AFF',
    },
    edge: {
      name: 'Edge',
      icon: 'fab fa-edge',
      color: '#0078D4',
    },
  },
  downloadStates: {
    pending: {
      label: 'Pending',
      color: '#6b7280',
      icon: 'fas fa-clock',
    },
    checking: {
      label: 'Checking',
      color: '#3b82f6',
      icon: 'fas fa-search',
    },
    downloading: {
      label: 'Downloading',
      color: '#f59e0b',
      icon: 'fas fa-download',
    },
    downloaded: {
      label: 'Downloaded',
      color: '#10b981',
      icon: 'fas fa-check-circle',
    },
    loginRequired: {
      label: 'Login Required',
      color: '#f59e0b',
      icon: 'fas fa-key',
    },
    notFound: {
      label: 'Not Found',
      color: '#ef4444',
      icon: 'fas fa-times-circle',
    },
    failed: {
      label: 'Failed',
      color: '#ef4444',
      icon: 'fas fa-exclamation-triangle',
    },
  },
  regions: [
    'Africa',
    'Antarctica',
    'Arctic',
    'Asia',
    'Europe',
    'Europe/Asia',
    'Middle East',
    'North America',
    'Oceania',
    'South America',
  ],
  dateFormats: {
    display: 'YYYY-MM-DD',
    filename: 'YYYYDDD',
    input: 'date',
  },
  api: {
    endpoints: {
      sonel: 'https://www.sonel.org/',
      nasa: 'https://cddis.nasa.gov/',
      unavco: 'https://data.unavco.org/',
    },
    cors: {
      enabled: false,
      proxy: null,
    },
  },
  features: {
    batchDownload: true,
    crossYearDateRange: true,
    stationSearch: true,
    datePickerToggle: true,
    progressTracking: true,
    authDetection: true,
    errorHandling: true,
  },
  version: '1.0.0',
  lastUpdated: '2024-12-19',
};

// Make the station list easily accessible
const stationList = globalConfig.gnssStations;
